name: manage-azure-policy-0e8e6564
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Azure_Monitor_Logs_for_Application_Insights_should_be_linked_to_a_Log_Analytics_workspace_d550e854-df1a-4de9-bf44-cd894b39a95e/**'
#      - .github/workflows/manage-azure-policy-0e8e6564.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_0e8e6564}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Azure_Monitor_Logs_for_Application_Insights_should_be_linked_to_a_Log_Analytics_workspace_d550e854-df1a-4de9-bf44-cd894b39a95e/**
