name: manage-azure-policy-e471b299
on:
  workflow_dispatch:
    inputs:
      remarks:
        description: 'Reason for triggering the workflow run'
        required: false
        default: 'Updating Azure Policies'


## Uncomment the following if you wish to automatically trigger workflow run with every commit
#
#  push:
#    paths:
#      - 'policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Log_Analytics_workspace_b889a06c-ec72-4b03-910a-cb169ee18721/**'
#      - .github/workflows/manage-azure-policy-e471b299.yml
jobs:
  apply-azure-policy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: ${{secrets.AZURE_CREDENTIALS_e471b299}}
        allow-no-subscriptions: true
    - name: Create or Update Azure Policies
      uses: azure/manage-azure-policy@v0
      with:
        paths: |
          policies/Deploy_Diagnostic_Settings_for_Logic_Apps_to_Log_Analytics_workspace_b889a06c-ec72-4b03-910a-cb169ee18721/**
